import { execFileSync } from "node:child_process";

export default async function globalSetup() {
	try {
		const env = { ...process.env };
		// The nested reporter run only generates fixture data; keep debug mode on the outer trace-viewer run.
		delete env.PWDEBUG;

		execFileSync("pnpm", ["--filter", "../reporter", "test:e2e"], {
			env: {
				...env,
				// Configure the reporter to send traces to our test trace-api-server
				PLAYWRIGHT_TRACE_API_ENDPOINT: "http://localhost:9295",
				// Clear OTLP endpoint to avoid conflicts
				OTEL_EXPORTER_OTLP_ENDPOINT: "",
				OTEL_EXPORTER_OTLP_HEADERS: "",
			},
			stdio: "pipe",
		});

		// Verify traces were created
		const traceIdsResponse = await fetch("http://localhost:9295/trace-ids");
		if (!traceIdsResponse.ok) {
			throw new Error("Failed to fetch trace IDs from trace-api-server");
		}

		const { traceIds } = (await traceIdsResponse.json()) as {
			traceIds: string[];
		};

		if (traceIds.length === 0) {
			console.warn(
				"Warning: No traces were generated by reporter e2e tests. Integration tests may fail.",
			);
		}
	} catch (error) {
		console.error("Failed to generate reporter trace data:");
		if (isExecError(error)) {
			const stdout = error.stdout?.toString().trim();
			const stderr = error.stderr?.toString().trim();

			if (stdout) console.error(stdout);
			if (stderr) console.error(stderr);
		} else {
			console.error(error);
		}
		throw error;
	}
}

function isExecError(error: unknown): error is {
	stdout?: Buffer;
	stderr?: Buffer;
} {
	return (
		typeof error === "object" &&
		error !== null &&
		("stdout" in error || "stderr" in error)
	);
}
