import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import path from "node:path";

export const BROWSER_PAGE_SPANS_TRACE_ID_FILE = path.resolve(
	"test-results/browser-page-spans-trace-id.txt",
);
export const BROWSER_PAGE_SPANS_TRACE_ZIP_PATH_FILE = path.resolve(
	"test-results/browser-page-spans-trace-zip-path.txt",
);
export const ERROR_SPANS_TRACE_ID_FILE = path.resolve(
	"test-results/error-spans-trace-id.txt",
);
export const SPAN_EVENTS_TRACE_ID_FILE = path.resolve(
	"test-results/span-events-trace-id.txt",
);

export default async function globalSetup() {
	try {
		const env = { ...process.env };
		// The nested reporter run only generates fixture data; keep debug mode on the outer trace-viewer run.
		delete env.PWDEBUG;
		mkdirSync(path.dirname(BROWSER_PAGE_SPANS_TRACE_ID_FILE), {
			recursive: true,
		});
		rmSync(BROWSER_PAGE_SPANS_TRACE_ID_FILE, { force: true });
		rmSync(BROWSER_PAGE_SPANS_TRACE_ZIP_PATH_FILE, { force: true });
		rmSync(ERROR_SPANS_TRACE_ID_FILE, { force: true });
		rmSync(SPAN_EVENTS_TRACE_ID_FILE, { force: true });

		execFileSync("pnpm", ["--filter", "../reporter", "test:e2e"], {
			env: {
				...env,
				// Configure the reporter to send traces to our test trace-api-server
				PLAYWRIGHT_TRACE_API_ENDPOINT: "http://localhost:9295",
				// Clear OTLP endpoint to avoid conflicts
				OTEL_EXPORTER_OTLP_ENDPOINT: "",
				OTEL_EXPORTER_OTLP_HEADERS: "",
				BROWSER_PAGE_SPANS_TRACE_ID_FILE,
				BROWSER_PAGE_SPANS_TRACE_ZIP_PATH_FILE,
				ERROR_SPANS_TRACE_ID_FILE,
				SPAN_EVENTS_TRACE_ID_FILE,
			},
			stdio: "pipe",
		});

		if (!existsSync(BROWSER_PAGE_SPANS_TRACE_ID_FILE)) {
			throw new Error(
				`Reporter e2e run did not write ${BROWSER_PAGE_SPANS_TRACE_ID_FILE}`,
			);
		}

		if (!existsSync(BROWSER_PAGE_SPANS_TRACE_ZIP_PATH_FILE)) {
			throw new Error(
				`Reporter e2e run did not write ${BROWSER_PAGE_SPANS_TRACE_ZIP_PATH_FILE}`,
			);
		}

		if (!existsSync(ERROR_SPANS_TRACE_ID_FILE)) {
			throw new Error(
				`Reporter e2e run did not write ${ERROR_SPANS_TRACE_ID_FILE}`,
			);
		}

		if (!existsSync(SPAN_EVENTS_TRACE_ID_FILE)) {
			throw new Error(
				`Reporter e2e run did not write ${SPAN_EVENTS_TRACE_ID_FILE}`,
			);
		}

		const traceZipPath = readFileSync(
			BROWSER_PAGE_SPANS_TRACE_ZIP_PATH_FILE,
			"utf-8",
		).trim();
		if (!existsSync(traceZipPath)) {
			throw new Error(`Reporter e2e run did not create ${traceZipPath}`);
		}

		// Verify traces were created
		const traceIdsResponse = await fetch("http://localhost:9295/trace-ids");
		if (!traceIdsResponse.ok) {
			throw new Error("Failed to fetch trace IDs from trace-api-server");
		}

		const { traceIds } = (await traceIdsResponse.json()) as {
			traceIds: string[];
		};

		if (traceIds.length === 0) {
			console.warn(
				"Warning: No traces were generated by reporter e2e tests. Integration tests may fail.",
			);
		}
	} catch (error) {
		console.error("Failed to generate reporter trace data:");
		if (isExecError(error)) {
			const stdout = error.stdout?.toString().trim();
			const stderr = error.stderr?.toString().trim();

			if (stdout) console.error(stdout);
			if (stderr) console.error(stderr);
		} else {
			console.error(error);
		}
		throw error;
	}
}

function isExecError(error: unknown): error is {
	stdout?: Buffer;
	stderr?: Buffer;
} {
	return (
		typeof error === "object" &&
		error !== null &&
		("stdout" in error || "stderr" in error)
	);
}
