import { execSync } from "node:child_process";

export default async function globalSetup() {
	console.log("Running reporter e2e tests to generate trace data...");

	try {
		const stdout = execSync("pnpm --filter ../reporter test:e2e", {
			env: {
				...process.env,
				// Configure the reporter to send traces to our test trace-api-server
				PLAYWRIGHT_TRACE_API_ENDPOINT: "http://localhost:9295",
				// Clear OTLP endpoint to avoid conflicts
				OTEL_EXPORTER_OTLP_ENDPOINT: "",
				OTEL_EXPORTER_OTLP_HEADERS: "",
			},
			stdio: "inherit",
		});

		console.log("Reporter e2e tests completed successfully");
		if (stdout) {
			console.log(stdout);
		}

		// Verify traces were created
		const traceIdsResponse = await fetch("http://localhost:9295/trace-ids");
		if (!traceIdsResponse.ok) {
			throw new Error("Failed to fetch trace IDs from trace-api-server");
		}

		const { traceIds } = (await traceIdsResponse.json()) as {
			traceIds: string[];
		};
		console.log(
			`Generated ${traceIds.length} trace(s): ${traceIds.join(", ")}`,
		);

		if (traceIds.length === 0) {
			console.warn(
				"Warning: No traces were generated by reporter e2e tests. Integration tests may fail.",
			);
		}
	} catch (error) {
		console.error("Failed to run reporter e2e tests:", error);
		throw error;
	}
}
